corvus-dotnet/Corvus.Deployment

- module/functions/azure/aad/Assert-RequiredResourceAccessContains.ps1
- module/functions/azure/aad/Get-AzureAdApplicationManifest.ps1
- module/functions/azure/aad/Test-AzureGraphAccess.ps1
- module/functions/azure/azcli/Invoke-AzCliRestCommand.ps1
Versions of the `Az.Accounts` module >1.9.5 no longer populate AzContext's `TokenCache` property, which we relied on when performing Graph API operations. (ref: https://github.com/Azure/azure-powershell/issues/13337)
This change alters the way we test for graph API access and uses the azure-cli `az rest` command to handle authenticating and calling the Graph API.
A future Az PowerShell release may extend the `Invoke-AzRestMethod` cmdlet to support more endpoints than just AzureRM, which should allow us to switch back to a pure PowerShell solution.
> Remove dependency on the TokenCache for accessing the Graph API

- .github/workflows/auto_release.yml
- .github/workflows/build.yml
- .github/workflows/publish_to_psgallery.yml
- module/arm-artifacts/shared-templates/synapse-workspace.json
- module/functions/Merge-Hashtables.Tests.ps1
- module/functions/Merge-Hashtables.ps1
- module/functions/azure/aad/Assert-RequiredResourceAccessContains.ps1
- module/functions/azure/aad/Get-AzureAdApplicationManifest.ps1
- module/functions/azure/azcli/Invoke-AzCli.ps1
- module/functions/azure/azcli/Invoke-AzCliRestCommand.ps1
* `Invoke-CorvusAzCli`: Logging of errors improved
* `Invoke-CorvusAzCliRestCommand`: The `Content-Type` header is now added by default to make calls to it more terse
* `Merge-CorvusHashtables`: Updated to support passing an array of hashtables to be merged
* `Assert-CorvusRequiredResourceAccessContains`: Fixed major bug and now uses more terse `Invoke-CorvusAzCliRestCommand` syntax
* `Get-CorvusAzureADApplicationManifest`: Updated to use more terse `Invoke-CorvusAzCliRestCommand` syntax
Update ARM templates:
* `synapse-workspace.json`: Now includes a default Spark Pool and fixes issue with child resources not being tagged
> Fixes issue with AzureAD application deployments and other minor improvements

- module/arm-artifacts/shared-templates/key-vault.json
- module/arm-artifacts/shared-templates/synapse-workspace.json
Updated ARM Templates:
* `key-vault.json`: Adds more complete tagging support
* `synapse-workspace`: Adds the default datalake storage account key as a template out
> Updates for adding key-vault support to synapse scenario

- module/functions/azure/aad/Assert-AzureAdAppRole.ps1
Function either adds new application role or updates existing one (if one exists with given ID).
This function is required by most (all?) Marain services' deployments.
> Add function for Assert-AzureAdAppRole

- .github/workflows/publish_to_dockerhub.yml
This should resolve the current deprecation error in this workflow.
> Bump version of 'docker/build-push-action'

- module/functions/Select-ExceptIn.Tests.ps1
- module/functions/Select-ExceptIn.ps1
New Cmdlets:
- `Select-ExceptIn` - Aims to emulate the 'Except' LINQ keyword to facilitate comparing collections of hashtable-based objects
> Adds 'Select-ExceptIn' function

- module/functions/Invoke-CommandWithRetry.Tests.ps1
- module/functions/Invoke-CommandWithRetry.ps1
Updated Cmdlets
* `Invoke-CommandWithRetry` - no longer masks the details of errors that cause a retry
> Updated 'Invoke-CommandWithRetry' to log more useful error messages

- module/arm-artifacts/shared-templates/storage-account.json
- module/arm-artifacts/shared-templates/synapse-workspace.json
Updated ARM Templates:
* `storage-account.json` :  Adds support for deploying a PrivateLink endpoint for the storage account
* `synapse-worksapce.son` : Adds support for configuring Synapse VNet integration and PrivateLink endpoints and resolves a bug with potential colliding RBAC assignment IDs
> Updated ARM templates for Synapse VNet integration and private link endpoints

- module/functions/azure/Invoke-ArmTemplateDeployment.ps1
- module/functions/azure/_DeployArmArtifacts.ps1
Updated Cmdlets
* `Invoke-ArmTemplateDeployment` - The `ArmTemplatePath` parameter can now reference an [Azure Bicep](https://github.com/Azure/bicep/) file, also adds the `DeploymentScope` parameter to support targetting different ARM deployment scopes
> Adds support for deploying Bicep templates

- module/Corvus.Deployment.psm1
- module/functions/azure/Invoke-ArmTemplateDeployment.ps1
Relaxes the hard requirement for having the `Az` modules installed when importing the module - a warning is now logged instead.
Updated Cmdlets
* `Invoke-ArmTemplateDeployment` - Added the `BicepVersion` parameter to make the bootstrapping process more flexible
> Improves Bicep CLI bootstrapping process

- Dockerfile
- module/functions/azure/Invoke-ArmTemplateDeployment.ps1
- module/functions/azure/azcli/Invoke-AzCliRestCommand.Tests.ps1
- module/functions/azure/azcli/Invoke-AzCliRestCommand.ps1
Updated Cmdlets
* `Invoke-AzCliRestMethod` - The `-Body` parameter is no longer restricted to being a `hashtable` type, so array-based request payloads are now supported
* `Invoke-ArmTemplateDeployment` - Default version of Bicep updated to v0.4.613
Updates the Docker image:
* Adds support for .Net 5.0 global tools
* Updates to PowerShell 7.1.4
* Updates to Bicep 0.4.613
* Latest Debian updates as of 23/09/2021
> Fixes Invoke-AzCliRestMethod not allowing array-based request payloads

- Dockerfile
- module/functions/azure/azcli/Invoke-AzCli.ps1
* `Invoke-AzCli` - Updated to workaround a behaviour change/bug in PowerShell `7.2.0` where `-ErrorVariable` does not capture messages sent to standard error stream.
> Fix issue with 'Invoke-AzCli' error handling

- module/Corvus.Deployment.psd1
The module already requires language version 6 or greater, however, this doesn't block the installation of the module on Windows PowerShell (i.e. v5.1) - it just prevents it from being imported and makes it invisible to `Get-Module`, which doesn't help diagnosing this scenario.
This change should ensure that attempts to install the module on older versions of PowerShell are explicitly blocked.
Technically this a breaking change, though the module would never have been usable on such versions of PowerShell that are now explcitly blocked.
> Added 'CompatiblePSEditions' to module manifest

- module/functions/azure/Invoke-ArmTemplateDeployment.ps1
- module/functions/azure/aad/Assert-AzureServicePrincipalForRbac.ps1
* `Assert-AzureServicePrincipalForRbac` - Added support for storing the service principal password in a Key Vault, also now uses Azure PowerShell instead of Azure CLI
* `Invoke-ArmTemplateDeployment` - Retries are now configurable, added `-WhatIf` support
> Add key vault support to 'Assert-AzureServicePrincipalForRbac'

- Dockerfile
- GitVersion.yml
- module/functions/New-Password.ps1
- module/functions/azure/Connect-Azure.ps1
- module/functions/azure/_EnsureAzureConnection.ps1
- module/functions/azure/_ValidateAzureConnectionDetails.ps1
- module/functions/azure/aad/Assert-AzureAdApiPermissions.ps1
- module/functions/azure/aad/Assert-AzureAdApp.ps1
- module/functions/azure/aad/Assert-AzureAdAppForAppService.ps1
- module/functions/azure/aad/Assert-AzureAdAppRole.ps1
- module/functions/azure/aad/Assert-AzureAdGroupMembership.Tests.ps1
- module/functions/azure/aad/Assert-AzureAdGroupMembership.ps1
- module/functions/azure/aad/Assert-AzureAdSecurityGroup.Tests.ps1
- module/functions/azure/aad/Assert-AzureAdSecurityGroup.ps1
- module/functions/azure/aad/Assert-AzureServicePrincipalForRbac.Tests.ps1
- module/functions/azure/aad/Assert-AzureServicePrincipalForRbac.ps1
- module/functions/azure/aad/Get-AzureAdDirectoryObject.Tests.ps1
- module/functions/azure/aad/Get-AzureAdDirectoryObject.ps1
- module/functions/azure/aad/Test-AzureGraphAccess.ps1
- module/functions/azure/azcli/Assert-AzCliLogin.ps1
- run-tests.ps1
This release marks the start of a general migration away from supporting the Azure Graph versions of the Azure PowerShell modules.
* `Assert-AzureAdSecurityGroup` - new option to relax strictness on idempotency checks, also no longer requires the azure-cli
* `Assert-AzureAdServicePrincipalForRbac` - updates to support running under least privilege identities, adds support for using service principal or application secrets
* `Connect-Azure` - now supports auto-login when the `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` environment variables are defined
New Cmdlets:
* `Assert-AzureAdGroupMembership` - handles managing group membership
* `Get-AzureAdDirectoryObject` - searches groups, users and service principals for a matching name or objectId
* `New-Password` - Generates a …
> AzureAD updates

- module/functions/configuration/Read-DeploymentConfig.ps1
- module/functions/configuration/_ResolveDeploymentConfigValues.Tests.ps1
- module/functions/configuration/_ResolveDeploymentConfigValues.ps1
- module/functions/configuration/handlers/_keyVaultSecretUriHandler.ps1
- run-tests.ps1
`DeploymentConfig` settings can now use the standard .NET configuration syntax to reference a value stored in Azure Key Vault Secrets:
`@Microsoft.KeyVault(SecretUri=https://<vault-name>.vault.azure.net/secrets/<secret-name>)`
`@Microsoft.KeyVault(SecretUri=https://<vault-name>.vault.azure.net/secrets/<secret-name>/<version-id>)`
For example:
```
@{
$storageAccountName = "myStorageAccount"
$storageAccessKey = "@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/StorageAccessKey)"
}
```
This initial implementation is built on an extensible mechanism for supporting other such external resolution scenarios.
> Add support for resolving deployment config settings via Key Vault secrets

- module/functions/azure/aad/Assert-AzureAdGroupMembership.ps1
- module/functions/azure/aad/Assert-AzureAdSecurityGroup.Tests.ps1
- module/functions/azure/aad/Assert-AzureAdSecurityGroup.ps1
- module/functions/azure/aad/Assert-AzureServicePrincipalForRbac.Tests.ps1
- module/functions/azure/aad/Assert-AzureServicePrincipalForRbac.ps1
- module/functions/azure/azcli/Assert-AzCliLogin.ps1
- module/functions/azure/azcli/Invoke-AzCli.Tests.ps1
- run-tests.ps1
This release fixes some issues identified in the 0.4.0 release.
- `Assert-AzureAdSecurityGroup` - Fixes issue with group owners being reported as not up-to-date when they are
- `Assert-AzureServicePrincipalForRbac` - Fixed bug whereby service principal credentials would not be stored in key vault
Also updates some of the Pester tests so they pass when running in `StrictMode`.
> AzureAD-related Fixes

- module/functions/azure/Connect-Azure.ps1
- module/functions/azure/aad/Assert-AzureAdApp.ps1
- module/functions/azure/aad/Assert-RequiredResourceAccessContains.ps1
- module/functions/azure/aad/Get-MicrosoftGraphApiAppUri.ps1
- `Connect-Azure` - Ensure the authentication logic understands the environment variable conventions typically used for managed identity scenarios
- `Assert-AzureAdApp` - Updated to support only versions of Azure PowerShell post the Microsoft Graph migration
- `Assert-RequiredResourceAccessContains` - Updated to support only versions of Azure PowerShell post the Microsoft Graph migration
Closes #82
Closes #83
> Make `Connect-Azure` aware of Managed Identity authentication scenarios

- module/functions/azure/aad/Assert-RequiredResourceAccessContains.ps1
Ensures the AAD App Registration details are always returned, even when unchanged by this cmdlet.
Resolves #84
> Fixed null return value in `Assert-RequiredResourceAccessContains`

- module/functions/azure/aad/Assert-AzureAdAppRole.Tests.ps1
- module/functions/azure/aad/Assert-AzureAdAppRole.ps1
- run-tests.ps1
- Updates the cmdlet to align with the wider strategy to only support MS Graph
- Improves checks to ensure `AppRoles` are not unnecessarily updated
- Adds some Pester test coverage
Closes #87
> Migrate `Assert-AzureAdAppRole` to only use MSGraph

- module/functions/azure/_HandleRestError.ps1
- module/functions/azure/aad/Assert-AzureAdGroupMembership.ps1
- module/functions/azure/aad/Assert-AzureServicePrincipalForRbac.Tests.ps1
- module/functions/azure/aad/Assert-AzureServicePrincipalForRbac.ps1
- module/functions/azure/aad/Assert-RequiredResourceAccessContains.ps1
- `Assert-AzureAdGroupMembership`
- `Assert-AzureServicePrincipalForRbac`
- `Assert-RequiredResourceAccessContains`
Also adds an internal helper function to handle this error checking.
> Fix issue with `Invoke-AzRestMethod` requests failing silently
